theme: jekyll-theme-slate
title: BooHoo kent13 Home.
author: Kent13
email: Kent13@boohoo.us
description: > # this means to ignore newlines until "baseurl:"
  A place I play with GitHub pages features
# social links
github_username:  kent13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
